Meal_Planner/MealPlanner/urls.py
from django.urls import path
from . import views

app_name = 'MealPlanner'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('random/', views.random, name='random'),
    path('get-recipes/', views.get_recipes, name='getRecipe'),
    path('new/', views.add_new_recipe, name='newRecipe'),
    path('profile/', views.profile_page, name='profile'),
    path('recipe-details/<int:id>', views.recipe_details, name='details'),
    path('delete/<int:id>', views.delete_recipe, name='delete')
]

Meal_Planner/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MealPlanner.urls')),
    path('users/', include('users.urls')),
]

Meal_Planner/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_view),
    path('logout/', views.logout_view),
    path('register/', views.register_view),
]

Meal_Planner/MealPlanner/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import MyUser
from jsonfield import JSONField

class Recipe(models.Model):
    recipe_id = models.IntegerField()
    recipe_name = models.CharField(max_length=200)

    recipe_info = JSONField(null=True)


    user = models.ForeignKey(MyUser, on_delete=models.PROTECT, related_name="favorite_recipes")

    def __str__(self):
        return self.recipe_name

Meal_Planner/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    ...

Meal_Planner/MealPlanner/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
import json

from .models import Recipe

def index(request):
    return render(request, 'MealPlanner/index.html')

def search(request):
    return render(request, 'MealPlanner/ingredients.html')

def random(request):
    return render(request, 'MealPlanner/randomRecipe.html')

def profile_page(request):
    recipes = request.user.favorite_recipes.all()
    context = {'recipes' : recipes,}
    return render(request, 'MealPlanner/profile_page.html', context)

def recipe_details(request, id):
    recipes = request.user.favorite_recipes.all()
    selected_recipe = get_object_or_404(Recipe, id=id, user=request.user)
    context = {
        'recipes' : recipes,
        'selected_recipe' : selected_recipe}
    return render(request, 'MealPlanner/recipeInfo.html', context)


def get_recipes(request, id):
    data = {'info': []}
    fav_recipes = get_object_or_404(Recipe, id=id, user=request.user)
    for recipe in fav_recipes:
        recipe_dict = {
            'id': recipe.recipe_id,
            'name': recipe.recipe_name
        }
        data['info'].append(recipe_dict)
    return JsonResponse(data)

def add_new_recipe(request):
    data = json.loads(request.body) 
    recipe_data = data.get('recipe')
    new_id = recipe_data.get('id')
    new_name = recipe_data.get('title')
    Recipe.objects.create(recipe_id=new_id, recipe_name=new_name, user=request.user, recipe_info=recipe_data)
    return JsonResponse({'message': 'OK'})

def delete_recipe(request, id):
    Recipe.objects.filter(id=id).delete()
    return redirect('MealPlanner:profile')

Meal_Planner/users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from .models import MyUser


def username_exists(username):
    return MyUser.objects.filter(username=username).exists()

def login_view(request):
    message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            message = 'invalid user credentials'
    context = {'message': message}
    return render(request, 'users/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('/')

def register_view(request):
    message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        
        if username_exists(username):
            message += ' username unavailable'

        if password1 != password2:
            message += ' passwords do not match'
        
        if message:
            context = {'message': message}
            return render(request, 'users/register.html', context)

        user = MyUser.objects.create_user(username=username, password=password1)
        login(request, user)
        return redirect('/')
        
    return render(request, 'users/register.html')

Meal_Planner/MealPlanner/templates/MealPlanner/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner: Home</title>
    <script src="https://unpkg.com/vue@next"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-stone-200">
    <header class="bg-indigo-200 border-2 border-indigo-200">
        <h1 class="text-4xl font-bold py-2 text-center">Welcome to the Meal Planner</h1>
        <h3 class="text-2xl font-semibold pb-3 text-center">A Meal Plan By You, FOR You!</h3>
        <nav class="flex lg:justify-evenly space-x-4 text-center mb-2">
            <a href='/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Home</a>
            {% if user.is_authenticated %}
            <a href='/search/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Search</a>
            <a href='/profile/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Profile</a>
            <a href='/random/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Random</a>
            <a href='/users/logout/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log Out</a>
            {% else %}
            <a href='/users/login/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log In</a>
            {% endif %}
        </nav>
    </header>
    <h1 class="p-2 text-4xl font-semibold text-center">-- Getting Started --</h1>
    <p class="p-3">Meal Planner was created for those who wish to create their own plans, are tired of making the same old thing and want new ideas, or for those that want to hold themselves accountable to what they create. To get started, first you must create your account. You can do that by clicking <a href="/users/register/" class="underline underline-offset-1 text-red-700">here</a> or clicking the "Log In" button at the top. Once you've created your account, you will have access to our Search function. This allows users to search a variety of different recipes using whatever ingredients they want or have available. The Meal Planner is not limited to one-ingredient searches at a time, you can search however many you want at once, such as mushrooms, rice, chicken, carrots, etc... The only limit to the search is what you have in your pantry!</p>

    <h1 class="p-2 text-4xl font-semibold text-center">-- After Registering --</h1>
    <p class="p-3">When you use the Search function, you will recieve a list back that gives you the options to view details and save. The "Details" button will pop up a side view with a photo, the ingredients, and directions on how to make it. If you like it, you can choose to "Save" it, which will then add it to your "Profile" tab that you can look at whenever you want. In your "Profile" tab, you will see a list of the recipes you have saved and the options to view the "Details" or to "Delete". The Details button will take you to a new page that contains all the information about the recipe you need. The required ingredients, a quick description, and the directions. If you decide that you don't like the recipe anymore, then simply go back to your Profile page and delete it!</p>

    <h1 class="p-2 text-4xl font-semibold text-center">-- Thank You For Visiting! --</h1>

    {% if user.is_authenticated %}

    <h1 class="p-2 text-4xl font-semibold text-center">-- An Example of A Recipe --</h1>
    <p class="p-3 text-center">The following is a randomly selected recipe for you to see as an example. You can only see this if you are logged in, so thank you for using my site! There is also the "Random" tab at the top, which does the same function.</p>
    <div id="app">

        <h2 class="p-2 text-3xl font-bold">[[ randomRecipeTitle ]]</h2>
        
        <img :src="randomRecipePhoto" class="p-4">

        <div v-html="randomRecipeSummary" class="mx-4"></div>

        <ol>
            <h3 class="p-2 text-2xl font-semibold">Ingredients:</h3>
            <li v-for="ingredient in randomRecipeIngredients" class="px-4 py-2">[[ ingredient.original ]]</li>
        </ol>
        <hr/>
        <h3 class="p-2 text-2xl font-semibold">Instructions:</h3>
        <div class="p-4" v-html="randomRecipeInstructions"></div>
    </div>

    <script>
        const App = {
            delimiters: ['[[', ']]'],
            data() {
                return {
                    randomRecipeInstructions: '',
                    randomRecipePhoto: '',
                    randomRecipeTitle: '',
                    randomRecipeSummary: '',
                    randomRecipeIngredients: [],
                }
            },

            created() {
                this.getRandomRecipe()
            },

            methods: {
                getRandomRecipe() {
                    axios({
                        method: 'get',
                        url: 'https://api.spoonacular.com/recipes/random',
                        headers: { Accept: 'application/json' },
                        params: { apiKey: 'c0706aec64ba455eb06753d6e855a6e5' }
                    })
                        .then(response => {
                            console.log(response.data.recipes)
                            this.randomRecipeInstructions = response.data.recipes[0].instructions
                            this.randomRecipePhoto = response.data.recipes[0].image
                            this.randomRecipeTitle = response.data.recipes[0].title
                            this.randomRecipeSummary = response.data.recipes[0].summary
                            this.randomRecipeIngredients = response.data.recipes[0].extendedIngredients
                        })
                }
            }

        }

        Vue.createApp(App).mount('#app')
    </script>
    {% endif %}

</body>
</html>

Meal_Planner/MealPlanner/templates/MealPlanner/ingredients.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner: Search</title>

    <script src="https://unpkg.com/vue@next"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-stone-200">
    <header class="bg-indigo-200 border-2 border-indigo-200">
        <h1 class="text-4xl font-bold py-2 text-center">The Meal Planner</h1>
        <h3 class="text-2xl font-semibold pb-3 text-center">A Meal Plan By You, FOR You!</h3>
        <nav class="flex lg:justify-evenly space-x-4 text-center mb-2">
            <a href='/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Home</a>
            {% if user.is_authenticated %}
            <a href='/search/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Search</a>
            <a href='/profile/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Profile</a>
            <a href='/random/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Random</a>
            <a href='/users/logout/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log Out</a>
            {% else %}
            <a href='/users/login/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log In</a>
            {% endif %}
        </nav>
    </header>
    {% if user.is_authenticated %}
    <div id="app">
        <form @submit.prevent="getRecipeByIngredient">
            {% csrf_token %}
            <label for="text" class="ml-2 mt-3 pl-3 font-semibold">Search by Ingredients:</label>
            <input v-model="userIngredient" type="text" id="text" class="border-2 border-slate-900 pl-2 mt-3 ml-2"/>
            <input type="submit" value="Submit" class="ml-2 px-2 mt-3 cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">
        </form>
        <hr />
        <div class="flex flex-row-reverse">
            <div class="w-1/2">
                <img v-if="showRecipeDetails" :src="[[ recipePhoto ]]">
                <ol v-if="showRecipeDetails" class="border-2 boder-indigo-400 font-semibold text-xl">Ingredients:
                    <li v-for="ingredient in recipeIngredients" class="ml-4 font-normal text-base">[[ ingredient.original ]]</li>
                </ol>
                <p v-if="showRecipeDetails" class="font-semibold text-xl">Instructions:</p>
                <p id="test" v-if="showRecipeDetails" v-html="showRecipeDetails" class="mx-2 px-2"></p>
            </div>
            <div class="w-1/2">
                <article v-for="recipe in userRecipes">
                    <span>
                        <p class="m-2 px-3 text-2xl font-semibold">
                            [[ recipe.title ]]
                            <a @click="getRecipeDetails(recipe)">
                                <button class="ml-2 mt-3 font-normal text-base cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">Details</button>
                            </a>
                            <a @click='saveRecipe(recipe)'>
                                <button class="ml-2 mt-3 font-normal text-base cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">Save</button>
                            </a>
                        </p>
                    </span>
                </article>
            </div>
        </div>
        </div>
        
        <script>
        const App = {
            delimiters: ['[[', ']]'],
            data() {
                return {
                    userIngredient: '',
                    userRecipes: [],
                    spotlightInstructions: {},
                    showRecipeDetails: '',
                    fullRecipeInfo: '',
                    recipeIngredients: [],
                    recipePhoto: ''
                }
            },

                mounted() {
                this.csrf_token = document.querySelector('input[name="csrfmiddlewaretoken"]').value
            },

            methods: {

                getRecipeByIngredient() {
                    axios({
                        method: 'get',
                        url: 'https://api.spoonacular.com/recipes/findByIngredients',
                        headers: { Accept: 'application/json' },
                        params: { apiKey: 'c0706aec64ba455eb06753d6e855a6e5', ingredients: this.userIngredient, number: 75 }
                    })
                        .then(response => {
                            // console.log(response.data)
                            this.userRecipes = response.data
                        })
                },

                getRecipeDetails(recipe) {
                    id = recipe.id
                    axios({
                        method: 'get',
                        url: `https://api.spoonacular.com/recipes/${id}/information`,
                        headers: { Accept: 'application/json' },
                        params: { apiKey: 'c0706aec64ba455eb06753d6e855a6e5' }
                    })
                        .then(response => {
                            this.showRecipeDetails = response.data.instructions
                            this.recipeIngredients = response.data.extendedIngredients
                            this.recipePhoto = response.data.image
                            console.log(this.recipePhoto)
                        })
                },

                saveRecipe(recipe) {
                    id = recipe.id
                    axios({
                        method: 'get',
                        url: `https://api.spoonacular.com/recipes/${id}/information`,
                        headers: { Accept: 'application/json' },
                        params: { apiKey: 'c0706aec64ba455eb06753d6e855a6e5' }
                    })
                        .then(response => {
                            // console.log(response.data)
                            this.showRecipeDetails = response.data.instructions
                            this.fullRecipeInfo = response.data
                            axios ({
                                method: 'post',
                                url: '/new/',
                                headers: { 'X-CSRFToken': this.csrf_token },
                                data: { 'recipe' : this.fullRecipeInfo }
                            })
                            .then(response => {
                                // this.getRecipeDetails(recipe)
                                console.log(response)
                            })
                        })
                    },
            }
        }
        Vue.createApp(App).mount('#app')
    </script>
    {% else %}
    <p class="p-4 font-semibold">You are currently not logged in. Please follow <a href="/users/login/" class="underline underline-offset-1 text-red-700">this link</a> to log in.</p>
    {% endif %}
</body>

</html>

Meal_Planner/MealPlanner/templates/MealPlanner/profile_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner: Profile</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-stone-200">
    <header class="bg-indigo-200 border-2 border-indigo-200">
        <h1 class="text-4xl font-bold py-2 text-center">The Meal Planner</h1>
        <h3 class="text-2xl font-semibold pb-3 text-center">A Meal Plan By You, FOR You!</h3>
        <nav class="flex lg:justify-evenly space-x-4 text-center mb-2">
            <a href='/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Home</a>
            {% if user.is_authenticated %}
            <a href='/search/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Search</a>
            <a href='/profile/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Profile</a>
            <a href='/random/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Random</a>
            <a href='/users/logout/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log Out</a>
            {% else %}
            <a href='/users/login/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log In</a>
            {% endif %}
        </nav>
    </header>
    {% if user.is_authenticated %}
    <h1 class="text-3xl font-semibold p-3">Welcome {{ user | title }} </h1>
    <div class="flex flex-wrap flex-row">
        <div>
            {% for recipe in recipes %}
            <div class="font-semibold text-xl py-3 px-6">
                {{ recipe.recipe_info.title }}
                <a href="{% url 'MealPlanner:details' recipe.id %}">
                    <button class="ml-2 mt-3 font-normal text-base cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">
                        Details
                    </button>
                </a>
                <a href="{% url 'MealPlanner:delete' recipe.id %}"> 
                    <button class="ml-2 mt-3 font-normal text-base cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">
                        Delete
                    </button>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <p class="p-4 font-semibold">Not sure how you got here, but please follow <a href="/users/login/" class="underline underline-offset-1 text-red-700">this link</a> to log in and view this page.</p>
    {% endif %}
</body>
</html>

Meal_Planner/MealPlanner/templates/MealPlanner/randomRecipe.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner: Random Recipe</title>

    <script src="https://unpkg.com/vue@next"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-stone-200">
    <header class="bg-indigo-200 border-2 border-indigo-200">
        <h1 class="text-4xl font-bold py-2 text-center">Welcome to the Meal Planner</h1>
        <h3 class="text-2xl font-semibold pb-3 text-center">A Meal Plan By You, FOR You!</h3>
        <nav class="flex lg:justify-evenly space-x-4 text-center mb-2">
            <a href='/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Home</a>
            {% if user.is_authenticated %}
            <a href='/search/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Search</a>
            <a href='/profile/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Profile</a>
            <a href='/random/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Random</a>
            <a href='/users/logout/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log Out</a>
            {% else %}
            <a href='/users/login/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log In</a>
            {% endif %}
        </nav>
    </header>
    <div id="app">

        <h2 class="p-2 text-3xl font-bold">[[ randomRecipeTitle ]]</h2>
        
        <img :src="randomRecipePhoto" class="p-4">

        <div v-html="randomRecipeSummary" class="mx-4"></div>

        <ol>
            <h3 class="p-2 text-2xl font-semibold">Ingredients:</h3>
            <li v-for="ingredient in randomRecipeIngredients" class="px-4 py-2">[[ ingredient.original ]]</li>
        </ol>
        <hr/>
        <h3 class="p-2 text-2xl font-semibold">Instructions:</h3>
        <div class="p-4" v-html="randomRecipeInstructions"></div>
    </div>

    <script>
        const App = {
            delimiters: ['[[', ']]'],
            data() {
                return {
                    randomRecipeInstructions: '',
                    randomRecipePhoto: '',
                    randomRecipeTitle: '',
                    randomRecipeSummary: '',
                    randomRecipeIngredients: [],
                }
            },

            created() {
                this.getRandomRecipe()
            },

            methods: {
                getRandomRecipe() {
                    axios({
                        method: 'get',
                        url: 'https://api.spoonacular.com/recipes/random',
                        headers: { Accept: 'application/json' },
                        params: { apiKey: 'c0706aec64ba455eb06753d6e855a6e5' }
                    })
                        .then(response => {
                            console.log(response.data.recipes)
                            this.randomRecipeInstructions = response.data.recipes[0].instructions
                            this.randomRecipePhoto = response.data.recipes[0].image
                            this.randomRecipeTitle = response.data.recipes[0].title
                            this.randomRecipeSummary = response.data.recipes[0].summary
                            this.randomRecipeIngredients = response.data.recipes[0].extendedIngredients
                        })
                }
            }

        }

        Vue.createApp(App).mount('#app')
    </script>
</body>

</html>

Meal_Planner/MealPlanner/templates/MealPlanner/recipeInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Planner: Recipe Info</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-stone-200">
    <header class="bg-indigo-200 border-2 border-indigo-200">
        <h1 class="text-4xl font-bold py-2 text-center">The Meal Planner</h1>
        <h3 class="text-2xl font-semibold pb-3 text-center">A Meal Plan By You, FOR You!</h3>
        <nav class="flex lg:justify-evenly space-x-4 text-center mb-2">
            <a href='/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Home</a>
            {% if user.is_authenticated %}
            <a href='/search/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Search</a>
            <a href='/profile/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Profile</a>
            <a href='/random/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Random</a>
            <a href='/users/logout/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log Out</a>
            {% else %}
            <a href='/users/login/' class="rounded-lg py-2 px-4 text-slate-700 font-medium border-4 bg-indigo-300 hover:bg-fuchsia-300">Log In</a>
            {% endif %}
        </nav>
    </header>
    {% if user.is_authenticated %}
    <div class="ml-3">
        <img class="ml-4 mb-2" src="{{ selected_recipe.recipe_info.image }}">
        <div class="text-xl font-bold">{{ selected_recipe.recipe_info.title }}</div>
        <div class="mx-3">{{ selected_recipe.recipe_info.summary | safe }}</div>
        {% if selected_recipe.recipe_info.extendedIngredients != None %}
        <ol class="text-xl font-semibold">Ingredients:
            {% for ingredient in selected_recipe.recipe_info.extendedIngredients %}
            <li class="text-base font-normal px-3">{{ ingredient.original }}</li>
            {% endfor %}
        </ol>
        <div class="text-xl font-semibold">Instructions:</div>
        {% endif %}
        <div class="text-base font-normal px-3">{{ selected_recipe.recipe_info.instructions | safe }}</div>
    </div>
    </div>
    <a href="{% url 'MealPlanner:profile' %}">
        <button class="ml-4 mt-3 px-2 font-normal text-base cursor-pointer border-2 border-indigo-400 rounded-lg bg-indigo-300 hover:bg-fuchsia-300">
            Return
        </button>
    </a>
    {% else %}
    <p class="p-4 font-semibold">You must be logged in to view this. Please follow <a href="/users/login/" class="underline underline-offset-1 text-red-700">this link</a> to log in.</p>
    {% endif %}

</body>
</html>